[server]
headless = true
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2c3e50"
textColor = "#ffffff"